<?php


namespace Zedstar16\HorizonCore\entities\EnvoyEntities;


use pocketmine\entity\Entity;
use pocketmine\item\Item;
use pocketmine\level\Level;
use pocketmine\math\Vector3;
use pocketmine\nbt\tag\CompoundTag;
use Zedstar16\HorizonCore\items\Fireworks;

class BaseEnvoyEntity extends Entity
{

    public $pos;

    public $animations_broadcasted = [false, false, false, false];

    public function __construct(Level $level, CompoundTag $nbt, Vector3 $spawnpos = null)
    {
        $this->pos = $spawnpos;
        parent::__construct($level, $nbt);
    }

    public function onUpdate(int $currentTick): bool
    {
        $dist = $this->y - $this->pos->y + 25;
        if ($dist > 10) {
            $this->motion->y = 0.15;
        } elseif ($dist > 3) {
            $this->motion->y = 0.075;
        } elseif ($dist > 0) {
            $this->motion->y = 0.025;
        } else {
            $this->motion->y = 0;
            if (!$this->animations_broadcasted[0]) {
                $firework = Item::get(Item::FIREWORKS);
                $color = Fireworks::COLOR_RED;
                $type = Fireworks::TYPE_HUGE_SPHERE;
                $firework->addExplosion($type, $color);
                $firework->setFlightDuration(2);
                $pos = new Vector3($this->x, $this->getFloorY() + 1, $this->z);
                $nbt = Entity::createBaseNBT($pos, new Vector3(0.001, 0.05, 0.001), lcg_value() * 360, 90);
                $entity = Entity::createEntity("ZedRPG", $this->getLevel(), $nbt, $firework);
                $entity->spawnToAll();
            }
        }
        return parent::onUpdate($currentTick); // TODO: Change the autogenerated stub
    }


}