<?php


namespace Zedstar16\HorizonCore\tasks\async;


use pocketmine\scheduler\AsyncTask;
use pocketmine\Server;
use Zedstar16\HorizonCore\cache\Cache;

class AsyncDataLoader extends AsyncTask
{
    /** @var array  */
    private $data = [];

    public function onRun()
    {
        $files =   array_diff(scandir("plugins/HorizonCore/resources/players"), ['..', '.']);
        foreach ($files as $filename){
            $file = json_decode(file_get_contents("plugins/HorizonCore/resources/players/" . $filename), true, 512, JSON_THROW_ON_ERROR);
            $this->data[substr($filename, 0, -5)] = $file;
        }
    }

    public function onCompletion(Server $server)
    {
        Cache::$data = $this->data;
        Server::getInstance()->getLogger()->notice("[HorizonCore] Loaded " . count($this->data) . " players into cache");
        parent::onCompletion($server); // TODO: Change the autogenerated stub
    }
}