<?php


namespace Zedstar16\HorizonCore\tasks\async;


use pocketmine\scheduler\AsyncTask;
use pocketmine\Server;
use Zedstar16\HorizonCore\cache\Cache;

class AsyncTopCalculator extends AsyncTask
{
    protected $datavalue, $result, $callable;

    public function __construct(string $datavalue, ?callable $callable)
    {
        $this->datavalue = $datavalue;
        $this->callable = $callable;
    }

    public function onRun()
    {
        $raw_data = Cache::$data;
        $list = [];
        foreach ($raw_data as $user => $data) {
            $list[$data["username-cased"]] = (float)$data[$this->datavalue];
        }
        sort($list, SORT_NUMERIC);
        $this->result = $list;
    }

    public function onCompletion(Server $server)
    {
        $callable = $this->callable;
        if($callable !== null){
            $callable($this->result);
        }
        parent::onCompletion($server); // TODO: Change the autogenerated stub
    }

}