<?php


namespace Zedstar16\HorizonCore\tasks\async;


use pocketmine\scheduler\AsyncTask;
use pocketmine\Server;
use Zedstar16\HorizonCore\cache\Cache;

class AsyncPlayerPositionCalculator extends AsyncTask
{
    protected $result, $callable;

    public function __construct(?callable $callable)
    {
        $this->callable = $callable;
    }

    public function onRun()
    {
        $raw_data = Cache::$data;

        $this->result = $list;
    }

    public function onCompletion(Server $server)
    {
        $callable = $this->callable;
        if ($callable !== null) {
            $callable($this->result);
        }
        parent::onCompletion($server); // TODO: Change the autogenerated stub
    }

}