<?php


namespace Zedstar16\HorizonCore\tasks\async;


use pocketmine\scheduler\AsyncTask;
use pocketmine\Server;
use Zedstar16\HorizonCore\cache\Cache;

class AsyncScheduledTopUpdate extends AsyncTask
{
    protected $result, $callable;

    public function __construct(?callable $callable)
    {
        $this->callable = $callable;
    }

    public function onRun()
    {
        $raw_data = Cache::$data;
        $datas = [];
        foreach ($raw_data as $player => $data) {
            $datas["experience"][$player] = $data["experience"];
            $datas["coins"][$player] = $data["coins"];
            $datas["kills"][$player] = $data["kills"];
            $datas["deaths"][$player] = $data["deaths"];
        }
        foreach ($datas as $key => $sub) {
            arsort($sub);
            $datas[$key] = $sub;
        }
        Cache::$top_data = $datas;
        $this->result = $datas;
    }

    public function onCompletion(Server $server)
    {
        $callable = $this->callable;
        if ($callable !== null) {
            $callable($this->result);
        }
        parent::onCompletion($server); // TODO: Change the autogenerated stub
    }

}